Remind about the upcoming interviews
tolstoyevsky/hubot-huntflow-reloaded pull request #23
Opened 2019-03-15 13:33 UTC by BehindLoader

2019-03-18 13:18 UTC, eugulixes commented on server/huntflow_reloaded/scheduler.py
> +    Create tasks in scheduler:
Schedules the events:
* remind an hour in advance;
* remind in the morning of the event day;
* remind in the evening of the event day.

2019-03-18 13:20 UTC, eugulixes commented on server/huntflow_reloaded/scheduler.py
> +    """ Wrapper for adding new task to scheduler """
`Shortcut for adding new events.`

2019-03-18 13:23 UTC, eugulixes commented on server/huntflow_reloaded/scheduler.py
> +    """ Function that will be called for notify about interview """
`Invoked when the event comes.`

2019-03-18 13:23 UTC, eugulixes commented on server/huntflow_reloaded/scheduler.py
> +    """ Run scheduler workers """
`Runs the scheduler workers.`

2019-03-20 08:52 UTC, polina-popova requested changes
While running I had a problem with the automatic determining of the local timezone.

2019-03-21 12:36 UTC, polina-popova requested changes
With current changes bot any time is sure that the interview is going to be in an hour (even if not)

2019-03-22 09:54 UTC, polina-popova approved these changes

2019-03-22 09:55 UTC, merged